
server:
  address: 0.0.0.0
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://127.0.0.1:3306/rbac-test?useUnicode=true&characterEncoding=utf-8&useSSL=false&useAffectedRows=true
    platform: mysql
mybatis:
  mapper-locations: classpath:mapper/*.xml



